---

# Required as Ubuntu ships with Python3 and not 2
ansible_python_interpreter: /usr/bin/python3

# System's timezone
configure_timezone: 'Europe/Madrid'

# Additional user to create
configure_user_name: 'hector'
configure_user_password: 'hector'
configure_user_groups: ['sudo', 'input', 'plugdev']

# List of apt-keys to load from disk
# See "extra_packages" role.
extra_packages_keys: []

# List of apt-keys to load from URLs.
# See "extra_packages" role
extra_packages_keys_url:
  - url: 'https://dl.google.com/linux/linux_signing_key.pub'
  - url: 'https://download.sublimetext.com/sublimehq-pub.gpg'
  - url: 'https://packages.microsoft.com/keys/microsoft.asc'
  - url: 'https://apt.releases.hashicorp.com/gpg'

# Extra apt repositories to add
# See "extra_packages" role
extra_packages_repositories:
  - name: 'google-chrome'
    repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
  - name: 'sublime_text'
    repo: 'deb https://download.sublimetext.com/ apt/stable/'
  - name: 'vscode'
    repo: 'deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main'
  - name: 'hashicorp'
    repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com jammy main'
  - name: 'slimbook'
    repo: 'ppa:slimbook/slimbook'

# Extra APT packages to install
# See "extra_packages" role
extra_packages_list:
  # Jumpcloud agent
  - apt-rdepends
  - apt-show-versions
  - coreutils
  - grep
  - hostname
  - libc-bin
  - libnss3
  - libnss3-tools
  - lsb-release
  - lsof
  - npm
  - mawk
  - openssl
  - passwd
  - procps
  - sysvinit-utils
  - sudo
  - tar

  # Everyday apps
  - 'gnome-calendar'
  - 'firefox'
  - 'google-chrome-stable'
  - 'libreoffice'
  - 'mythes-gl'
  - 'hyphen-gl'

  # Programming
  - 'sublime-text'
  - 'code'
  - 'clang-format'
  - 'cppcheck'
  - 'fonts-firacode'
  - 'git'
  - 'python3'
  - 'pylint'
  - 'python3-pip'
  - 'shellcheck'
  - 'sqlite3'

  # Infra stuff
  - 'vagrant'
  - 'virtualbox'
  - 'terraform'
  - 'packer'

  # CLI tools
  - 'terminator'
  - 'iotop'
  - 'iftop'
  - 'ngrep'
  - 'mysql-client'
  - 'postgresql-client-14'
  - 'strace'
  - 'telnet'
  - 'telnet-ssl'
  - 'unrar'
  - 'unzip'
  - 'vim'
  - 'nmap'
  - 'jq'
  - 'whois'

  # Media
  - 'vlc'
  - 'gimp'

  # System utils
  - 'gpg'
  - 'gparted'
  - 'p7zip'
  - 'p7zip-full'
  - 'default-jdk'
  - 'network-manager-l2tp'
  - 'network-manager-l2tp-gnome'
  - 'network-manager-openvpn'
  - 'network-manager-openvpn-gnome'
  - 'network-manager-pptp'
  - 'network-manager-pptp-gnome'
  - 'sshpass'
  - 'remmina'
  - 'remmina-plugin-vnc'
  - 'telnet-ssl'

  # System
  - 'libinput-tools'
  - 'etckeeper'
  - 'powerline'
  - 'libfuse2'
  - 'libfuse3-3'
  - 'mdadm'
  - 'slimbookbattery'

  # Laptop-specific
  - 'ecryptfs-utils'

# Snap packages to install
extra_packages_snaps:
  - name: 'spotify'
  - name: 'bitwarden'
  - name: 'phpstorm'
    classic: true
  - name: 'dbeaver-ce'
  - name: 'postman'
  - name: 'telegram-desktop'
    channel: 'latest/beta'

# Pip packages to install
extra_packages_pip:
  - name: 'ansible'
    executable: 'pip3'
  - name: 'ansible-lint'
    executable: 'pip3'
  - name: 'ansible-navigator'
    executable: 'pip3'
  - name: 'molecule'
    executable: 'pip3'
  - name: 'molecule[docker]'
    executable: 'pip3'
  - name: 'molecule[vagrant]'
    executable: 'pip3'
  - name: 'yamllint'
    executable: 'pip3'
  - name: 'docker'
    executable: 'pip3'
  - name: 'molecule-vagrant'
    executable: 'pip3'
  - name: 'python-vagrant'
    executable: 'pip3'

# NPM utils
extra_packages_npm:
  - name: 'jshint'
    global: true

docker_apt_release_channel: 'stable'

# Docker users
docker_users: ["{{ configure_user_name}}"]

# Git configuration for the .gitconfig file
git_config:
  user:
    name: 'Héctor Luaces'
    email: "{{ vault_email }}"
    signingkey: '33835F136C261136'
  core:
    editor: 'vi'
    excludesfile: '~/.gitignore'
    fileMode: 'false'
  web:
    browser: 'firefox'
  color:
    diff: 'auto'
    status: 'auto'
    branch: 'auto'
    interactive: 'auto'
    ui: 'true'
    pager: 'true'
  # This helps Go access private repos
  'url "git@github.com:"':
    insteadOf: 'https://github.com/'
  commit:
    gpgsign: 'true'

# Configuration files for the newly created user
configuration_files_user:
  # Terminator
  - type: 'file'
    src: 'terminator/config'
    dest: '~/.config/terminator/config'

  # Private keys
  - type: 'file'
    src: 'ssh/config_work_user'
    dest: '~/.ssh/config'
    dest_mode: '700'
    mode: '600'
  - type: 'file'
    src: 'ssh/work'
    dest: '~/.ssh/work'
    dest_mode: '700'
    mode: '600'
  - type: 'file'
    src: 'ssh/work.pub'
    dest: '~/.ssh/work.pub'
    dest_mode: '700'
    mode: '600'
  - type: 'file'
    src: 'ssh/git'
    dest: '~/.ssh/git'
    dest_mode: '700'
    mode: '600'

# aws-cli configuration
awscli_configuration: "{{ vault_awscli_configuration }}"


gsettings_defaults:
  # Gnome: Dark theme
  - key: '/org/gnome/desktop/interface/gtk-theme'
    value: "'Yaru-purple-dark'"
  - key: '/org/gnome/desktop/interface/icon-theme'
    value: "'Yaru-purple'"

  # Gnome: hide mounts & trash from the dock
  - key: '/org/gnome/shell/extensions/dash-to-dock/show-mounts'
    value: 'false'
  - key: '/org/gnome/shell/extensions/dash-to-dock/show-trash'
    value: 'false'

  # Gnome: Night light
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-enabled'
    value: 'true'
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-temperature'
    value: 'uint32 3140'
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic'
    value: 'true'

  # Gnome: Screenshots shortcuts
  - key: '/org/gnome/shell/keybindings/show-screenshot-ui'
    value: '["<Primary><Shift><Alt>4"]'
  - key: '/org/gnome/shell/keybindings/show-screen-recordingui'
    value: '["<Primary><Shift><Alt>r"]'
  - key: '/org/gnome/shell/keybindings/screenshot'
    value: '["<Alt>3"]'
  - key: '/org/gnome/shell/keybindings/screenshot-window'
    value: '["<Shift><Alt>periodcentered"]'

  # Gnome: navigation
  - key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-right'
    value: '["<Primary><Alt>Down"]'
  - key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-left'
    value: '["<Primary><Alt>Up"]'
  - key: '/org/gnome/desktop/wm/keybindings/move-to-workspace-right'
    value: '["<Primary><Shift><Alt>Down"]'
  - key: '/org/gnome/desktop/wm/keybindings/move-to-workspace-left'
    value: '["<Primary><Shift><Alt>Up"]'

  # Gnome: Custom keybindings
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings'
    value: '["/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/","/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/"]'

  # Gnome: Custom keybinding #0: tilix quake dropdown
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding'
    value: "'masculine'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command'
    value: "'env GDK_BACKEND=x11 tilix --quake'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name'
    value: "'tilix --quake'"

  # Gnome: Custom keybinding #1: show ulauncher
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding'
    value: "'<Primary><Shift>space'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command'
    value: "'ulauncher-toggle'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name'
    value: "'ulauncher'"

  # Gnome: Emoji selector (conflicts with a keybinding for terminator)
  - key: '/org/freedesktop/ibus/panel/emoji/hotkey'
    value: '["<Primary><Shift>underscore"]'

  # Gnome: Calendar configuration
  - key: '/org/gnome/desktop/calendar/show-weekdate'
    value: 'true'
  - key: '/org/gnome/desktop/interface/clock-show-date'
    value: 'true'

  # Gnome: show battery percent
  - key: '/org/gnome/desktop/interface/show-battery-percentage'
    value: 'true'

  # Gnome: Move the "applications button" at top
  - key: '/org/gnome/shell/extensions/dash-to-dock/show-apps-at-top'
    value: 'true'

  # Gnome: Dock on all screens
  - key: '/org/gnome/shell/extensions/dash-to-dock/multi-monitor'
    value: 'true'

  # Gnome: Element size on dock
  - key: '/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size'
    value: '48'

  # Gnome: Privacy
  - key: '/org/gnome/desktop/privacy/send-software-usage-stats'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/report-technical-problems'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/remember-app-usage'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/remove-old-temp-files'
    value: 'true'
  - key: '/org/gnome/desktop/privacy/remember-recent-files'
    value: 'false'
