---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:00"
      timezone: "CET"
    groups:
      molecule:
        patterns:
          - "molecule"
          - "molecule-plugins*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:00"
      timezone: "CET"
