---
- name: 'Converge'
  hosts: 'ubuntu_group'
  become: false
  gather_facts: true
  vars:
    dotfiles_git_config:
      user:
        name: 'Molecule Test'
        email: 'molecule@example.com'
      core:
        editor: 'vim'
  roles:
    - 'hluaces.iac.dotfiles'
