---
all:
  vars:
    hluaces_molecule_libvirt_pool_name: 'mol-ubuntu24-desktop'
    hluaces_molecule_libvirt_network_name: 'mol-u24-dsk'
    hluaces_molecule_libvirt_network_bridge: 'virbr-mdsk'
    hluaces_molecule_libvirt_network_cidr: '192.168.125.0/24'
    hluaces_molecule_libvirt_base_image_url: >-
      https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
    hluaces_molecule_libvirt_vm_vcpus: 4
    hluaces_molecule_libvirt_vm_memory_mb: 4096
    hluaces_molecule_libvirt_vm_disk_gb: 30
    ansible_user: 'molecule'
    ansible_ssh_private_key_file: >-
      {{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY')
         | default('/var/tmp/molecule-libvirt', true) }}/ssh_key
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  children:
    ubuntu_group:
      hosts:
        ubuntu24-desktop:
          ansible_host: '192.168.125.11'
