---
namespace: hluaces


name: collection_template
version: 1.0.0
readme: README.md

authors:
  - Héctor Luaces <hluaces@github>

description: |
  This is an example collection

repository: https://github.com/hluaces-ansible/collection-template

documentation: https://github.com/hluaces-ansible/collection-template

homepage: https://github.com/hluaces-ansible/collection-template

issues: https://github.com/hluaces-ansible/collection-template

license:
  - 'BSD'

tags: []

dependencies: {}

build_ignore: []
