---

- name: 'Manage gsettings/dconf preferences'
  community.general.dconf:
    key: "{{ item['key'] }}"
    value: "{{ item['value'] | string }}"
    state: "{{ item['state'] | default('present') }}"
  loop: "{{ gsettings }}"

- name: 'Configure the "Privacy -> Connectivity check" option (1/2)'
  community.general.ini_file:
    path: '/var/lib/NetworkManager/NetworkManager-intern.conf'
    section: 'connectivity'
    option: '.set.enabled'
    values: "{{ gsettings_conectivty_check | ternary('true', 'false') }}"
    no_extra_spaces: true
    create: true
  become: true
  become_user: 'root'

- name: 'Configure the "Privacy -> Connectivity check" option (1/2)'
  ansible.builtin.file:
    path: '/etc/NetworkManager/conf.d/20-connectivity-ubuntu.conf'
    state: "{{ gsettings_conectivty_check | ternary('touch', 'absent') }}"
    access_time: 'preserve'
    modification_time: 'preserve'
  become: true
  become_user: 'root'
