---

- name: 'Install Dropbox dependencies'
  ansible.builtin.apt:
    update_cache: true
    state: 'present'
    name:
      - 'procps'
      - 'python3-gi'
      - 'libatk1.0-0'
      - 'gpg'

- name: 'Add Dropbox GPG key'
  ansible.builtin.apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: '1C61A2656FB57B7E4DE0F4C1FC918B335044912E'

# Dropbox is prone to serve 404s, so this task is here to minimise blips
- name: 'Download the Dropbox .deb package'
  ansible.builtin.get_url:
    url: "{{ dropbox_deb_package_url }}"
    dest: "{{ dropbox_tmp_deb_file }}"
    force: true
    mode: "0600"
  register: dropbox_get_dropbox
  until: not dropbox_get_dropbox.failed
  retries: 5
  delay: 20

- name: 'Install the Dropbox .deb package'
  ansible.builtin.apt:
    deb: "{{ dropbox_tmp_deb_file }}"
    state: 'present'
  when: ansible_facts['distribution_file_variety'] == 'Debian'

# Noble seems to have transient issues with the repo, so this works around it
- name: 'Use the jammy repository on Ubuntu noble'
  ansible.builtin.replace:
    path: '/etc/apt/sources.list.d/dropbox.list'
    regexp: 'noble'
    replace: 'focal'
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_release == 'noble'
