---

# Required as Ubuntu ships with Python3 and not 2
ansible_python_interpreter: /usr/bin/python3

# System's timezone
configure_system_timezone: 'Europe/Madrid'

# Additional user to create
configure_system_user_name: 'hector'
configure_system_user_password: 'hector'
configure_system_user_groups: ['sudo', 'input', 'plugdev']

# List of extra repositories:
extra_packages_deb822_repositories:
  - name: 'sublime'
    types: 'deb'
    architectures: 'amd64'
    uris: 'https://download.sublimetext.com/'
    suites: 'apt/stable/'
    signed_by: 'https://download.sublimetext.com/sublimehq-pub.gpg'
  - name: 'vscode'
    types: 'deb'
    architectures: 'amd64,arm64,armhf'
    uris: 'https://packages.microsoft.com/repos/code '
    suites: 'stable'
    components: 'main'
    signed_by: 'https://packages.microsoft.com/keys/microsoft.asc'
  - name: 'hashicorp'
    types: 'deb'
    architectures: 'amd64'
    uris: 'https://apt.releases.hashicorp.com'
    suites: 'noble'
    components: 'main'
    signed_by: 'https://apt.releases.hashicorp.com/gpg'
  - name: 'mozilla'
    types: 'deb'
    architectures: 'amd64'
    uris: 'https://packages.mozilla.org/apt'
    suites: 'mozilla'
    components: 'main'
    signed_by: 'https://packages.mozilla.org/apt/repo-signing-key.gpg'
  - name: 'github-cli'
    types: 'deb'
    architectures: 'amd64'
    uris: 'https://cli.github.com/packages'
    suites: 'stable'
    components: 'main'
    signed_by: 'https://cli.github.com/packages/githubcli-archive-keyring.gpg'

# [deprecated] Legacy packages and keys. These utilities write their own
# `*.list` files, which would cause the system to fail if they were to be
# managed with deb8222 repositories
extra_packages_keys_url:
  - url: 'https://dl.google.com/linux/linux_signing_key.pub'

# [deprecated] Extra apt repositories to add
# See "extra_packages" role
extra_packages_repositories:
  - name: 'google-chrome'
    repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'

# Extra APT packages to install
# See "extra_packages" role
extra_packages_list:
  # Everyday apps
  - 'gnome-calendar'
  - 'google-chrome-stable'
  - 'hyphen-gl'
  - 'libreoffice'
  - 'mythes-gl'

  # Programming
  - 'code'
  - 'fonts-firacode'
  - 'git-filter-repo'
  - 'git'
  - 'git-delta'
  - 'luarocks'
  - 'nodejs'
  - 'npm'
  - 'python3-pip'
  - 'python3'
  - 'sqlite3'
  - 'sublime-text'

  # Linting
  - 'ansible-lint'
  - 'clang-format'
  - 'cppcheck'
  - 'lua-check'
  - 'pylint'
  - 'shellcheck'
  - 'yamllint'

  # Ansible
  - 'ansible'
  - 'python3-docker'
  - 'vagrant'
  - 'virtualbox'

  # Infra stuff
  - 'terraform'
  - 'packer'

  # CLI tools
  - 'acpi'
  - 'curl'
  - 'gh'
  - 'gpg'
  - 'iftop'
  - 'iotop'
  - 'jq'
  - 'mysql-client'
  - 'ngrep'
  - 'nmap'
  - 'p7zip-full'
  - 'p7zip'
  - 'postgresql-client-16'
  - 'powertop'
  - 'sqlite3'
  - 'strace'
  - 'telnet-ssl'
  - 'telnet'
  - 'terminator'
  - 'tree'
  - 'unrar'
  - 'unzip'
  - 'vim'
  - 'whois'

  # Modern CLI tools
  - 'bat'
  - 'duf'
  - 'eza'
  - 'fzf'
  - 'gping'
  - 'httpie'
  - 'zoxide'

  # Media
  - 'easyeffects'
  - 'gimp'
  - 'vlc'

  # System utils
  - 'default-jdk'
  - 'etckeeper'
  - 'gnutls-bin'
  - 'gparted'
  - 'libfuse2'
  - 'libfuse3-3'
  - 'libinput-tools'
  - 'mdadm'
  - 'network-manager-l2tp-gnome'
  - 'network-manager-l2tp'
  - 'network-manager-openvpn-gnome'
  - 'network-manager-openvpn'
  - 'network-manager-pptp-gnome'
  - 'network-manager-pptp'
  - 'powerline'
  - 'remmina-plugin-vnc'
  - 'remmina'
  - 'sshpass'

  # Laptop-specific
  - 'ecryptfs-utils'

# Snap packages to install
extra_packages_snaps:
  # Firefox is installed via apt
  - name: 'firefox'
    state: 'absent'

  # Everyday apps
  - name: 'dbeaver-ce'
  - name: 'spotify'
  - name: 'telegram-desktop'
    channel: 'latest/beta'

  # CLI
  - name: 'tflint'
  - name: 'terraform-docs'
  - name: 'yt-dlp'
  - name: 'kubectl'
    classic: true

  # Modern CLI
  - name: 'bottom'
    plugs: ["mount-observe", "hardware-observe", "system-observe", "process-control"]
  - name: 'cheat'
  - name: 'fx'

  # Programming
  - name: 'phpstorm'
    classic: true
  - name: 'postman'
  - name: 'go'
    classic: true
  - name: 'golangci-lint'
    classic: true

# NPM utils
extra_packages_npm:
  - name: 'jshint'
    global: true

docker_apt_release_channel: 'stable'

# Docker users
docker_users: ["{{ configure_system_user_name }}"]

# Git configuration for the .gitconfig file
dotfiles_git_config:
  user:
    name: 'Héctor Luaces'
    email: "{{ vault_email }}"
    signingkey: '11A11DEBC6EC8723'
  core:
    editor: 'vi'
    excludesfile: '~/.gitignore'
    fileMode: 'false'
    pager: 'delta'
  interactive:
    diffFilter: 'delta --color-only'
  delta:
    navigate: 'true'
    dark: 'true'
  merge:
    conflictStyle: 'zdiff3'
  web:
    browser: 'firefox'
  color:
    diff: 'auto'
    status: 'auto'
    branch: 'auto'
    interactive: 'auto'
    ui: 'true'
    pager: 'true'
  # This helps Go access private repos
  'url "git@github.com:"':
    insteadOf: 'https://github.com/'
  commit:
    gpgsign: 'true'

# Configuration files for the newly created user
configuration_files_user:
  # Terminator
  - type: 'file'
    src: 'terminator/config'
    dest: '~/.config/terminator/config'

  # Git configuration for colum width
  - type: 'file'
    src: 'gitcommit.vim'
    dest: '~/.vim/after/ftplugin/gitcommit.vim'
    dest_mode: '700'
    mode: '600'

  # Private keys
  - type: 'file'
    src: 'ssh/config_work_user'
    dest: '~/.ssh/config'
    dest_mode: '700'
    mode: '600'
  - type: 'file'
    src: 'ssh/work'
    dest: '~/.ssh/work'
    dest_mode: '700'
    mode: '600'
  - type: 'file'
    src: 'ssh/work.pub'
    dest: '~/.ssh/work.pub'
    dest_mode: '700'
    mode: '600'
  - type: 'file'
    src: 'ssh/git'
    dest: '~/.ssh/git'
    dest_mode: '700'
    mode: '600'

# aws-cli configuration
awscli_configuration: "{{ vault_awscli_configuration }}"

gsettings_defaults:
  # Gnome: Dark theme
  - key: '/org/gnome/desktop/interface/gtk-theme'
    value: "'Yaru-purple-dark'"
  - key: '/org/gnome/desktop/interface/icon-theme'
    value: "'Yaru-purple'"

  # Gnome: hide mounts & trash from the dock
  - key: '/org/gnome/shell/extensions/dash-to-dock/show-mounts'
    value: 'false'
  - key: '/org/gnome/shell/extensions/dash-to-dock/show-trash'
    value: 'false'

  # Gnome: Move the "applications button" at top
  - key: '/org/gnome/shell/extensions/dash-to-dock/show-apps-at-top'
    value: 'true'

  # Gnome: Dock on all screens
  - key: '/org/gnome/shell/extensions/dash-to-dock/multi-monitor'
    value: 'true'

  # Gnome: Element size on dock
  - key: '/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size'
    value: '48'

  # Gnome: auto hide dock and extend it
  - key: '/org/gnome/shell/extensions/dash-to-dock/dock-fixed'
    value: 'false'
  - key: '/org/gnome/shell/extensions/dash-to-dock/extend-height'
    value: 'true'

  # Gnome: Night light
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-enabled'
    value: 'true'
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-temperature'
    value: 'uint32 3140'
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic'
    value: 'true'

  # Gnome: Screenshots shortcuts
  - key: '/org/gnome/shell/keybindings/show-screenshot-ui'
    value: '["<Primary><Shift><Alt>4"]'
  - key: '/org/gnome/shell/keybindings/show-screen-recordingui'
    value: '["<Primary><Shift><Alt>r"]'
  - key: '/org/gnome/shell/keybindings/screenshot'
    value: '["<Alt>3"]'
  - key: '/org/gnome/shell/keybindings/screenshot-window'
    value: '["<Shift><Alt>periodcentered"]'

  # Gnome: navigation
  - key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-right'
    value: '["<Primary><Alt>Down"]'
  - key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-left'
    value: '["<Primary><Alt>Up"]'
  - key: '/org/gnome/desktop/wm/keybindings/move-to-workspace-right'
    value: '["<Primary><Shift><Alt>Down"]'
  - key: '/org/gnome/desktop/wm/keybindings/move-to-workspace-left'
    value: '["<Primary><Shift><Alt>Up"]'

  # Gnome: Custom keybindings
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings'
    value: '["/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/","/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/"]'

  # Gnome: Custom keybinding #0: tilix quake dropdown
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding'
    value: "'<Alt>masculine'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command'
    value: "'env GDK_BACKEND=x11 tilix --quake'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name'
    value: "'tilix --quake'"

  # Gnome: Custom keybinding #1: show ulauncher
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding'
    value: "'<Primary><Shift>space'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command'
    value: "'ulauncher-toggle'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name'
    value: "'ulauncher'"

  # Gnome: Emoji selector (conflicts with a keybinding for terminator)
  - key: '/org/freedesktop/ibus/panel/emoji/hotkey'
    value: '["<Primary><Shift>underscore"]'

  # Gnome: Calendar configuration
  - key: '/org/gnome/desktop/calendar/show-weekdate'
    value: 'true'
  - key: '/org/gnome/desktop/interface/clock-show-date'
    value: 'true'

  # Gnome: show battery percent
  - key: '/org/gnome/desktop/interface/show-battery-percentage'
    value: 'true'

  # Gnome: enable hot corners
  - key: '/org/gnome/desktop/interface/enable-hot-corners'
    value: 'true'

  # Gnome: enable edge tiling
  - key: '/org/gnome/mutter/edge-tiling'
    value: 'true'

  # Gnome: Fractional scaling. Prevents issues on multi-monitors setups
  # See: https://github.com/micheleg/dash-to-dock/issues/435
  - key: '/org/gnome/mutter/experimental-features'
    value: ['scale-monitor-framebuffer']

  # Gnome: Privacy
  - key: '/org/gnome/desktop/privacy/send-software-usage-stats'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/report-technical-problems'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/remember-app-usage'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/remove-old-temp-files'
    value: 'true'
  - key: '/org/gnome/desktop/privacy/remember-recent-files'
    value: 'false'
