---

################################################################################
# Actions
################################################################################
gsettings_default_action: true

# Configures or not the "gsettings" variable through dconf
gsettings_do_gsettings: "{{ gsettings_default_action }}"

################################################################################
# Variables
################################################################################

# Gsettings value
gsettings: "{{ gsettings_defaults + gsettings_extra }}"
# - key:
#   value:
#   state:

gsettings_defaults:
  # Gnome: Dark theme
  - key: '/org/gnome/desktop/interface/gtk-theme'
    value: "'Yaru-dark'"

  # Gnome: Night light
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-enabled'
    value: 'true'
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-temperature'
    value: 'uint32 3140'
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic'
    value: 'true'

  # Gnome: Screenshots shortcuts
  - key: '/org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip'
    value: '["<Primary><Shift><Alt>dollar"]'
  - key: '/org/gnome/settings-daemon/plugins/media-keys/window-screenshot'
    value: '["<Alt>Print"]'
  - key: '/org/gnome/settings-daemon/plugins/media-keys/area-screenshot'
    value: '["<Shift><Alt>dollar"]'
  - key: '/org/gnome/settings-daemon/plugins/media-keys/screenshot-clip'
    value: '["<Alt>3"]'
  - key: '/org/gnome/settings-daemon/plugins/media-keys/window-screenshot-clip'
    value: '["<Shift><Alt>periodcentered"]'

  # Gnome: Custom keybindings
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings'
    value: '["/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/"]'

  # Gnome: Custom keybinding #0: tilix quake dropdown
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding'
    value: "'masculine'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command'
    value: "'tilix --quake'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name'
    value: "'tilix --quake'"

  # Gnome: Emoji selector (conflicts with a keybinding for terminator)
  - key: '/org/freedesktop/ibus/panel/emoji/hotkey'
    value: '["<Control><Shift>space"]'

  # Gnome: Calendar configuration
  - key: '/org/gnome/desktop/calendar/show-weekdate'
    value: 'true'
  - key: '/org/gnome/desktop/interface/clock-show-date'
    value: 'true'

  # Gnome: Move the "applications button" at top
  - key: '/org/gnome/shell/extensions/dash-to-dock/show-apps-at-top'
    value: 'true'

  # Gnome: Privacy
  - key: '/org/gnome/desktop/privacy/send-software-usage-stats'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/report-technical-problems'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/remember-app-usage'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/remove-old-temp-files'
    value: 'true'
  - key: '/org/gnome/desktop/privacy/remember-recent-files'
    value: 'false'

gsettings_extra: []

# Enables or not the "Privacy -> Conectivity check" option
gsettings_conectivty_check: false
