---
prerun: false

driver:
  name: vagrant
platforms:
  - name: "${MOLECULE_SCENARIO_NAME}"
    box: hluaces/ubuntu-gnome
    box_version: 24.04.06
    memory: 4096
    cpus: 4
    groups: ['ubuntu_group']
    config_options:
      vm.boot_timeout: 300
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../inventory/group_vars
      host_vars: ../../inventory/host_vars
  env:
    ANSIBLE_CONFIG: "${MOLECULE_PROJECT_DIRECTORY}/ansible.cfg"
scenario:
  test_sequence:
    - dependency
    # - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    # - cleanup
    - destroy
