---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/collections/requirements.yml

ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --diff
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/inventory/

scenario:
  name: ubuntu24-laptop
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
