# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box         = "hluaces/ubuntu-gnome"
  config.vm.box_version = "20.04"
  config.ssh.insert_key = false
  vagrant_root          = File.dirname(__FILE__)

  config.vm.provider "virtualbox" do |vb|
    vb.cpus   = "8"
    vb.gui    = true
    vb.memory = "4096"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook       = "../playbooks/ubuntu-install.yml"
    ansible.config_file    = "../ansible.cfg"
    ansible.verbose        = "vv"
    ansible.inventory_path = "../inventory/default.ini"
    ansible.limit          = "ubuntu20-laptop,localhost"
  end
end
