# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu20-desktop", primary: true do |ubuntu|
    ubuntu.vm.box         = "hluaces/ubuntu-gnome"
    ubuntu.vm.box_version = "20.04.04"
  end

  config.vm.define "ubuntu20-laptop" do |ubuntu|
    ubuntu.vm.box         = "hluaces/ubuntu-gnome"
    ubuntu.vm.box_version = "20.04.04"
  end

  config.vm.define "ubuntu22-desktop" do |ubuntu|
    ubuntu.vm.box         = "hluaces/ubuntu-gnome"
    ubuntu.vm.box_version = "22.04.01"
  end

  config.ssh.insert_key = false
  vagrant_root          = File.dirname(__FILE__)

  config.vm.provider "virtualbox" do |vb|
    vb.cpus   = "8"
    vb.gui    = true
    vb.memory = "4096"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook       = "../playbooks/ubuntu-install.yml"
    ansible.config_file    = "../ansible.cfg"
    ansible.inventory_path = "../inventory/default.ini"
    ansible.limit          = "ubuntu20-laptop,localhost"
    ansible.verbose        = "vv"
    ansible.raw_arguments  = Shellwords.shellsplit(ENV['ANSIBLE_ARGS']) if ENV['ANSIBLE_ARGS']
  end
end
