---
galaxy_info:
  role_name: 'sysctl'
  namespace: 'hluaces'
  author: 'Héctor Luaces'
  description: 'Applies kernel parameters through sysctl'
  license: 'GPL-2.0-or-later'
  min_ansible_version: '2.17'
  platforms:
    - name: 'Ubuntu'
      versions:
        - 'noble'
  galaxy_tags: []

dependencies: []
