---
- name: 'Install Joplin dependencies'
  ansible.builtin.apt:
    update_cache: true
    name: 'libfuse'
    state: 'present'

- name: 'Download and execute Joplin install script'
  ansible.builtin.shell: "wget -O - {{ joplin_install_script }} | bash"
  environment:
    TERM: 'xterm-256color'
  tags: ['skip_ansible_lint']
