---
all:
  vars:
    hluaces_molecule_scenario_index: 11
    hluaces_molecule_scenario_code: 'tzn'
    hluaces_molecule_docker_image: 'geerlingguy/docker-ubuntu2404-ansible:latest'
  children:
    ubuntu_group:
      hosts:
        timezone:
          ansible_connection: 'community.docker.docker'
          ansible_host: "{{ hluaces_molecule_docker_container_name }}"
