---
galaxy_info:
  author: Héctor Luaces <hector@luaces-novo.es>
  role_name: awscli
  namespace: hluaces
  description: Installs and configures aws-cli plus aws-vault
  company: ''
  license: 'MIT'
  min_ansible_version: 2.8

  platforms:
    - name: 'Ubuntu'
      versions: ['20.04']

  galaxy_tags: []
  dependencies: []
