---
galaxy_info:
  author: Héctor Luaces <hector@luaces-novo.es>
  role_name: hadolint
  namespace: hluaces
  description: Installs hadolint
  license: MIT
  min_ansible_version: '2.8'

  platforms:
    - name: 'Ubuntu'
      versions: ['focal']
  galaxy_tags: []
dependencies: []
