---
name: Install scaleway-cli
description: Installs scaleway-cli

inputs:
  arch:
    description: Architecture for the binary.
    default: 'amd64'
    required: false
  version:
    description: Version tag to install.
    default: '2.39.0'
    required: false
  install_path:
    description: Full absolute path where the binary will be installed.
    default: '/usr/local/bin/scw'
    required: false
  default_region:
    type: choice
    description: Default region to set.
    default: 'fr-par'
    required: false
    options: [fr-par, nl-ams, pl-waw]
  default_zone:
    type: choice
    description: Default zone to set.
    default: 'fr-par-2'
    required: false
    options:
      - fr-par-1
      - fr-par-2
      - fr-par-3
      - nl-ams-1
      - nl-ams-2
      - nl-ams-3
      - pl-waw-1
      - pl-waw-2
      - pl-waw-3

runs:
  using: composite
  steps:
    - name: Cache Scaleway-cli
      uses: actions/cache@v4
      with:
        path: ${{ inputs.install_path }}
        key: scaleway-cli-${{ inputs.arch }}-${{ inputs.version }}

    - name: Download Scaleway-cli version ${{ inputs.version }}
      shell: bash
      run: |
        wget -q -O ${{ inputs.install_path }} https://github.com/scaleway/scaleway-cli/releases/download/v${{ inputs.version }}/scaleway-cli_${{ inputs.version }}_linux_${{ inputs.arch }}
        chmod +x ${{ inputs.install_path }}

    - name: Set default region
      shell: bash
      run: |
        mkdir -p ~/.config/scw
        touch /home/runner/.config/scw/config.yaml
        ${{ inputs.install_path }} config set default-region=${{ inputs.default_region }}
        ${{ inputs.install_path }} config set default-zone=${{ inputs.default_zone }}
