---

- name: 'Manage NPM packages'
  community.general.npm:
    name: "{{ item.name }}"
    global: "{{ item.global | default(false) }}"
    version: "{{ item.version | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    ignore_scripts: "{{ item.ignore_scripts | default(false) }}"
  loop: "{{ extra_packages_npm }}"
