---

- name: 'Configure PIP packages'
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    extra_args: "{{ item.extra_args | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ extra_packages_pip }}"
