---

- name: 'Disable apt-daily services to unlock dpkg'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'stopped'
    enabled: false
  loop: "{{ apt_lock_holders }}"
  notify: ['enable apt_lock_holders']

- name: 'Stop apt-daily-upgrade.timer'
  ansible.builtin.systemd:
    name: 'apt-daily-upgrade.timer'
    state: 'stopped'
    enabled: 'no'

- name: "Refresh apt-cache (apt-get update)"
  ansible.builtin.apt:
    update_cache: true

- name: 'Update Ubuntu Drivers'
  ansible.builtin.command: 'ubuntu-drivers autoinstall'
  when: ansible_virtualization_role != 'guest'
  failed_when: false
  changed_when: true

- name: 'Install base packages'
  ansible.builtin.apt:
    name:
      # So that ansible does not complain. See issue #56832 @ ansible
      - aptitude
      - ubuntu-restricted-extras
      - gnome-tweaks
      - apt-transport-https
      # This is actually required by the module
      - pipx
    state: 'present'
