---

- name: 'Configure SNAP packages'
  community.general.snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel | default('stable') }}"
    classic: "{{ item.classic | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ extra_packages_snaps }}"
