---

# This guy fucks
# https://github.com/nagygergo/jetbrains-toolbox-install/blob/master/jetbrains-toolbox.sh
- name: 'JetBrains Toolbox | Obtain download metadata'
  uri:
    url: "https://data.services.jetbrains.com//products/releases?code=TBA&latest=true&type=release"
    force: true
    return_content: true
    status_code: [200, 304]
    http_agent: ([
      'Mozilla/5.0 (X11; Linux x86_64)',
      'AppleWebKit/537.36 (KHTML, like Gecko)',
      'Chrome/59.0.3071.115 Safari/537.36')']|shuffle)[0]
    headers:
      Origin: 'https://www.jetbrains.com'
      Accept-Encoding: 'gzip, deflate, br'
      Accept-Language: 'en_US,en;q=0.8'
      Accept: 'application/json, text/javascript, */*; q=0.01'
      Referrer: 'https://www.jetbrains.com/toolbox/download/'
  register: _jetbrains_data
  tags: ['skip_ansible_lint']

- name: 'JetBrains Toolbox | Convert returned data to a variable'
  set_fact:
    _jetbrains_data: "{{ _jetbrains_data.content|from_json }}"

- name: "JetBrains Toolbox | Download build {{ _jetbrains_data.TBA[0].build }}"
  get_url:
    url: "{{ _jetbrains_data.TBA[0].downloads.linux.link }}"
    force: true
    dest: "/tmp/jetbrains-toolbox.tar.gz"

- name: 'JetBrains Toolbox | Create destination dir'
  file: path="~/bin" state='directory'

- name: 'JetBrains Toolbox | Extract package to destination dir'
  unarchive:
    extra_opts: ['--strip-components=1']
    remote_src: true
    src: "/tmp/jetbrains-toolbox.tar.gz"
    dest: "~/bin"

- name: 'JetBrains Toolbox | Remove temp file'
  file: path="/tmp/jetbrains-toolbox.tar.gz" state='absent'
