---

- name: "Apply sysctl configuration"
  ansible.posix.sysctl:
    name: "{{ item['key'] }}"
    ignoreerrors: "{{ item['value']['ignoreerrors'] | default(omit) }}"
    reload: "{{ item['value']['reload'] | default(omit) }}"
    state: "{{ item['value']['state'] | default(omit) }}"
    sysctl_file: "{{ item['value']['sysctl_file'] | default(omit) }}"
    sysctl_set: "{{ item['value']['sysctl_set'] | default(omit) }}"
    value: "{{ item['value']['value'] | default(omit) }}"
  loop: "{{ sysctl_configuration | dict2items }}"
