---
- name: Create network
  ansible.builtin.include_tasks: create.yml
  when: hluaces_molecule_libvirt_state == 'present'

- name: Destroy network
  ansible.builtin.include_tasks: destroy.yml
  when: hluaces_molecule_libvirt_state == 'absent'
