---
hluaces_molecule_libvirt_state: present  # noqa: var-naming[no-role-prefix]
hluaces_molecule_libvirt_uri: "qemu:///system"  # noqa: var-naming[no-role-prefix]

hluaces_molecule_libvirt_pool_name: molecule  # noqa: var-naming[no-role-prefix]
hluaces_molecule_libvirt_pool_type: dir  # noqa: var-naming[no-role-prefix]
hluaces_molecule_libvirt_pool_path: "/var/tmp/molecule-libvirt/{{ hluaces_molecule_libvirt_pool_name }}"  # noqa: var-naming[no-role-prefix]
hluaces_molecule_libvirt_pool_mode: "0755"  # noqa: var-naming[no-role-prefix]
hluaces_molecule_libvirt_pool_autostart: true  # noqa: var-naming[no-role-prefix]

# LVM-specific
hluaces_molecule_libvirt_pool_devices: []  # noqa: var-naming[no-role-prefix]
hluaces_molecule_libvirt_pool_vg_name: null  # noqa: var-naming[no-role-prefix]
# ZFS-specific
hluaces_molecule_libvirt_pool_zfs_name: null  # noqa: var-naming[no-role-prefix]

# Libvirt ownership — override for non-Debian systems (RHEL uses qemu/qemu)
hluaces_molecule_libvirt_user: libvirt-qemu  # noqa: var-naming[no-role-prefix]
hluaces_molecule_libvirt_group: kvm  # noqa: var-naming[no-role-prefix]

# Base image
hluaces_molecule_libvirt_base_image_url: >-  # noqa: var-naming[no-role-prefix]
  https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
hluaces_molecule_libvirt_base_image_name: null  # noqa: var-naming[no-role-prefix]
