---
all:
  vars:
    hluaces_molecule_scenario_index: 10
    hluaces_molecule_scenario_code: 'mln'
    hluaces_molecule_docker_image: 'geerlingguy/docker-ubuntu2404-ansible:latest'
  children:
    ubuntu_group:
      hosts:
        moonlander:
          ansible_connection: 'community.docker.docker'
          ansible_host: "{{ hluaces_molecule_docker_container_name }}"
