---

- name: 'Create destination dir'
  file:
    path: "{{ ditem['dest'] }}"
    state: 'directory'
    owner: "{{ ditem['dest_owner']|default(omit) }}"
    group: "{{ ditem['dest_group']|default(omit) }}"
    mode: "{{ ditem['dest_mode']|default(omit) }}"


- name: 'Clone remote repository'
  git:
    accept_hostkey: "{{ ditem['accept_hostkey']|default(omit) }}"
    key_file: "{{ ditem['key_file']|default(omit) }}"
    repo: "{{ ditem['repo']|default(omit) }}"
    ssh_opts: "{{ ditem['ssh_opts']|default(omit) }}"
    version: "{{ ditem['version']|default(omit) }}"
    dest: "{{ ditem['dest']|default(omit) }}"
    force: "{{ ditem['force']|default(false) }}"
