---

- name: 'Create destination dir'
  file:
    path: "{{ item.dest }}"
    state: 'directory'
    owner: "{{ item.dest_owner|default(omit) }}"
    group: "{{ item.dest_group|default(omit) }}"
    mode: "{{ item.dest_mode|default(omit) }}"


- name: 'Clone remote repository'
  git:
    accept_hostkey: "{{ item.accept_hostkey|default(omit) }}"
    key_file: "{{ item.key_file|default(omit) }}"
    repo: "{{ item.repo|default(omit) }}"
    ssh_opts: "{{ item.ssh_opts|default(omit) }}"
    version: "{{ item.version|default(omit) }}"
    dest: "{{ item.dest|default(omit) }}"
    accept_hostkey: "{{ item.accept_hostkey|default(true) }}"
    force: "{{ item.force|default(false) }}"
