---

- name: 'Install Ubuntu Workstation (root configuration)'
  hosts: 'ubuntu_group'
  remote_user: "{{ remote_user | default(omit) }}"
  become_user: 'root'
  become: true
  roles:
    - role: 'configure_system'
      tags: ['role-configure_system']
    - role: 'hluaces.iac.sysctl'
      tags: ['role-sysctl']
    - role: 'hluaces.iac.extra_packages'
      tags: ['role-extra_packages']
    - role: 'geerlingguy.docker'
      tags: ['role-geerlingguy.docker']
    - role: 'hluaces.gnome.dropbox'
      tags: ['role-dropbox']
    - role: 'hadolint'
      tags: ['role-hadolint']

    # Root dotfiles
    - role: 'hluaces.iac.dotfiles'
      tags: ['role-dotfiles']

    # Root only installs this, configuration is per-user
    - role: 'awscli'
      vars:
        awscli_default_action: false
        awscli_do_install: true
        awscli_install_method: 'snap'
      tags: ['role-awscli']

    # Only installation
    - role: 'hluaces.gnome.ulauncher'
      vars:
        ulauncher_default_action: false
        ulauncher_do_install: true
      tags: ['role-ulauncher']

  post_tasks:
    - name: 'Include extra tasks for root user'
      ansible.builtin.include_tasks:
        file: "{{ item }}"
        apply:
          tags: ['privileged-extra-tasks']
      with_fileglob: "{{ playbook_dir }}/tasks/{{ inventory_hostname }}/root/*"
      tags: ['privileged-extra-tasks']

- name: 'Install Ubuntu Workstation (non root configuration)'
  hosts: 'ubuntu_group'
  remote_user: "{{ remote_user | default(omit) }}"
  become: true
  become_user: "{{ configure_user_name }}"
  roles:
    - role: 'hluaces.iac.pip'
      tags: ['role-pip']
    - role: 'hluaces.iac.dotfiles'
      tags: ['role-dotfiles']
    - role: 'hluaces.iac.configuration_files'
      tags: ['role-configuration_files']
      vars:
        configuration_files: "{{ configuration_files_user }}"
    - role: 'hluaces.gnome.gsettings'
      tags: ['role-gsettings']
    - role: 'hluaces.gnome.tilix'
      tags: ['role-tilix']
    - role: 'hluaces.gnome.joplin'
      tags: ['role-joplin']
    # The user only configures this
    - role: 'awscli'
      vars:
        awscli_default_action: false
        awscli_do_configure: true
      tags: ['role-awscli']
    # The user only configures this
    - role: 'hluaces.gnome.ulauncher'
      vars:
        ulauncher_default_action: false
        ulauncher_do_configure: true
      tags: ['role-ulauncher']
  post_tasks:
    - name: 'Include extra tasks for non-privileged users'
      ansible.builtin.include_tasks:
        file: "{{ item }}"
        apply:
          tags: ['unprivileged-extra-tasks']
      with_fileglob: "{{ playbook_dir }}/tasks/{{ inventory_hostname }}/user/*"
      tags: ['unprivileged-extra-tasks']
