---
- name: 'Build vendor packages'
  import_playbook: 0_local_requirements.yaml

- name: 'Install Ubuntu Workstation (root configuration)'
  hosts: 'ubuntu_group'
  remote_user: "{{ remote_user | default(omit) }}"
  become_user: root
  become: true
  roles:
    - role: configure_system
      tags: ['role-configure_system']
    - role: extra_packages
      tags: ['role-extra_packages']
    - role: geerlingguy.docker
      tags: ['role-geerlingguy.docker']
    # Root dotfiles
    - role: dotfiles
      tags: ['role-dotfiles']
    - role: 'awscli'
      tags: ['role-awscli']
  post_tasks:
    - name: 'Include extra tasks for root user'
      include_tasks:
        file: "{{ item }}"
        apply:
          tags: ['privileged-extra-tasks']
      with_fileglob: "{{ playbook_dir }}/tasks/root/*"
      tags: ['privileged-extra-tasks']

- name: 'Install Ubuntu Workstation (non root configuration)'
  hosts: 'ubuntu_group'
  remote_user: "{{ remote_user | default(omit) }}"
  become: true
  become_user: "{{ configure_user_name }}"
  roles:
    - role: dotfiles
      tags: ['role-dotfiles']
    - role: configuration_files
      tags: ['role-configuration_files']
      vars:
        configuration_files: "{{ configuration_files_user }}"
    - role: gsettings
      vars:
        gsettings: "{{ gnome_settings }}"
      tags: ['role-gsettings']
    - role: tilix
      tags: ['role-tilix']
    - role: joplin
      tags: ['role-joplin']
  post_tasks:
    - name: 'Include extra tasks for non-privileged users'
      include_tasks:
        file: "{{ item }}"
        apply:
          tags: ['unprivileged-extra-tasks']
      with_fileglob: "{{ playbook_dir }}/tasks/user/*"
      tags: ['unprivileged-extra-tasks']
