---

- name: 'Install Ubuntu Workstation (non root configuration)'
  hosts: 'ubuntu_group'
  remote_user: "{{ remote_user | default(omit) }}"
  become: true
  become_user: "vagrant"
  roles:
    - role: 'joplin'
      tags: ['role-joplin']
