---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: collections.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: centos7
    image: centos:7
  - name: debian_stable
    image: debian:stable
provisioner:
  name: ansible
  log: true
  options:
    forks: '20'
  config_options:
    defaults:
      strategy: ${MOLECULE_STRATEGY-linear}
      strategy_plugins: ${MOLECULE_STRATEGY_PLUGINS}
      force_color: true
