---
name: Lint
run-name: Lint for ${{ github.event_name }}:${{ github.ref }} (${{ github.sha }})
"on":
  push:
    branches: main
  pull_request:
  schedule:
    - cron: "0 7 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      ################
      # Caches
      ################
      - name: Cache Ansible Galaxy roles
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: roles/vendors
          key: ansible-galaxy-roles-${{ hashFiles('roles/requirements.yml') }}

      - name: Cache Ansible Galaxy collections
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: collections/vendors
          key: ansible-galaxy-collections-${{ hashFiles('collections/requirements.yml') }}

      ################
      # Bootstrapping
      ################
      - name: Set up APT dependencies
        run: sudo apt update && sudo apt install -y make libvirt-dev pkg-config

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap
        with:
          vault-password: "hello world"
          vault-file: "~/.ansible/default.vault"

      ################
      # Linting
      ################
      - name: Lint (ansible-lint)
        run: ansible-lint

      - name: Lint (yamllint)
        run: yamllint -s .

  Actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Run actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0
