---
name: Lint
run-name: Lint for ${{ github.event_name }}:${{ github.ref }} (${{ github.sha }})
"on":
  push:
    branches: main
  pull_request:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      ################
      # Caches
      ################
      - name: Cache Ansible Galaxy roles
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: roles/vendors
          key: ansible-galaxy-roles-${{ hashFiles('roles/requirements.yml') }}

      - name: Cache Ansible Galaxy collections
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: collections/vendors
          key: ansible-galaxy-collections-${{ hashFiles('collections/requirements.yml') }}

      ################
      # Bootstrapping
      ################
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.12"

      - name: Set up APT dependencies
        run: sudo apt update && sudo apt install -y make libvirt-dev pkg-config

      - name: Set up Ansible dependencies
        run: make dependencies

      - name: Set up Ansible Vault
        run: echo "hello world" > ~/.ansible/default.vault && chmod 600 ~/.ansible/default.vault

      ################
      # Linting
      ################
      - name: Lint (ansible-lint)
        run: ansible-lint

      - name: Lint (yamllint)
        run: yamllint -s .
