---
name: Build new release
on:
  push:
    branches:
      - main

jobs:
  Build new release:
    runs-on: ubuntu-latest
    steps:
      - uses: rymndhng/release-on-push-action@v0.27.0
        with:
          bump_version_scheme: patch
          tag_prefix: ""
          use_github_release_notes: true
