---
name: Build new release
on:
  push:

jobs:
  Build-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: rymndhng/release-on-push-action@v0.27.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch
          tag_prefix: "test"
          use_github_release_notes: true
